"""add logged_out_at to user model

Revision ID: 748a591e8f77
Revises: 8c1c82baffe8
Create Date: 2026-07-14 19:47:10.017139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '748a591e8f77'
down_revision: Union[str, Sequence[str], None] = '8c1c82baffe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('logged_out_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'logged_out_at')
    # ### end Alembic commands ###
