"""update storage limit cap to users

Revision ID: 7b438977379f
Revises: 748a591e8f77
Create Date: 2026-07-26 20:10:21.653291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b438977379f'
down_revision: Union[str, Sequence[str], None] = '748a591e8f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column('users', 'storage_limit_bytes',
               existing_type=sa.Integer(),
               server_default='15728640',
               existing_nullable=False)

    # 2. OPTIONAL: Update EXISTING users who currently have the old 50MB default!
    # (Only run this if you want to lower the limit for existing users as well)
    op.execute("UPDATE users SET storage_limit_bytes = 15728640 WHERE storage_limit_bytes = 52428800")

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'storage_limit_bytes',
               existing_type=sa.Integer(),
               server_default='52428800',
               existing_nullable=False)
               
    op.execute("UPDATE users SET storage_limit_bytes = 52428800 WHERE storage_limit_bytes = 15728640")
    # ### end Alembic commands ###
